"""
Nginx Service — rewrites the Nginx config to HTTPS after setup completion.
"""
import os
import subprocess
import shutil
from pathlib import Path


NGINX_AVAILABLE = Path("/etc/nginx/sites-available/orbit")
NGINX_ENABLED   = Path("/etc/nginx/sites-enabled/orbit")
NGINX_CONF_D    = Path("/etc/nginx/conf.d/orbit.conf")
ORBIT_HOME      = Path(os.environ.get("ORBIT_HOME", "/opt/orbit"))


def write_https_nginx_config(fqdn: str, cert_path: str, key_path: str,
                              app_port: int = 8080) -> tuple[bool, str]:
    """
    Write a production-grade HTTPS Nginx config and reload Nginx.
    Returns (success, message).
    """
    config = f"""# Orbit — HTTPS Production Config
# Auto-generated by Orbit first-time setup wizard
# DO NOT EDIT — managed by Orbit. Use the Setup page to make changes.

# Redirect HTTP → HTTPS
server {{
    listen 80;
    listen [::]:80;
    server_name {fqdn};
    return 301 https://$host$request_uri;
}}

server {{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name {fqdn};

    # ── TLS ───────────────────────────────────────────────────────────────────
    ssl_certificate           {cert_path};
    ssl_certificate_key       {key_path};
    ssl_protocols             TLSv1.2 TLSv1.3;
    ssl_ciphers               ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers off;
    ssl_session_cache         shared:SSL:10m;
    ssl_session_timeout       10m;
    ssl_session_tickets       off;
    ssl_stapling              on;
    ssl_stapling_verify       on;

    # ── Security Headers ──────────────────────────────────────────────────────
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;
    add_header X-Frame-Options           "SAMEORIGIN"                                   always;
    add_header X-Content-Type-Options    "nosniff"                                      always;
    add_header X-XSS-Protection          "1; mode=block"                                always;
    add_header Referrer-Policy           "strict-origin-when-cross-origin"              always;
    add_header Permissions-Policy        "geolocation=(), microphone=(), camera=()"     always;
    add_header Content-Security-Policy   "default-src 'self'; script-src 'self' 'unsafe-inline' cdn.jsdelivr.net; style-src 'self' 'unsafe-inline' cdn.jsdelivr.net fonts.googleapis.com; font-src 'self' fonts.gstatic.com cdn.jsdelivr.net; img-src 'self' data: blob:; connect-src 'self'; frame-ancestors 'none';" always;

    client_max_body_size 20M;

    # ── Static Files ──────────────────────────────────────────────────────────
    location /static/ {{
        alias {ORBIT_HOME}/app/static/;
        expires 7d;
        add_header Cache-Control "public, immutable";
        access_log off;
    }}

    location /uploads/ {{
        alias {ORBIT_HOME}/app/static/uploads/;
        expires 1d;
        access_log off;
    }}

    # ── Gunicorn Proxy ────────────────────────────────────────────────────────
    location / {{
        proxy_pass         http://127.0.0.1:{app_port};
        proxy_http_version 1.1;
        proxy_set_header   Host              $host;
        proxy_set_header   X-Real-IP         $remote_addr;
        proxy_set_header   X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header   X-Forwarded-Proto $scheme;
        proxy_set_header   Upgrade           $http_upgrade;
        proxy_set_header   Connection        "upgrade";
        proxy_redirect     off;
        proxy_read_timeout 120s;
        proxy_connect_timeout 10s;
        proxy_send_timeout 120s;
        proxy_buffering    on;
        proxy_buffer_size  8k;
    }}

    # ── Setup page blocked post-setup ─────────────────────────────────────────
    location /setup {{
        return 302 /admin;
    }}

    # ── Block hidden files ────────────────────────────────────────────────────
    location ~ /\\. {{
        deny all;
        access_log off;
        log_not_found off;
    }}

    access_log /var/log/nginx/orbit_access.log;
    error_log  /var/log/nginx/orbit_error.log warn;
}}
"""

    try:
        target = NGINX_AVAILABLE if NGINX_AVAILABLE.parent.exists() else NGINX_CONF_D
        target.write_text(config)

        # Re-link if using sites-available/enabled pattern
        if NGINX_AVAILABLE.parent.exists() and not NGINX_ENABLED.exists():
            NGINX_ENABLED.symlink_to(NGINX_AVAILABLE)

        # Test config
        result = subprocess.run(["nginx", "-t"],
                                capture_output=True, text=True, timeout=10)
        if result.returncode != 0:
            return False, f"Nginx config test failed:\n{result.stderr}"

        # Reload
        subprocess.run(["systemctl", "reload", "nginx"],
                       check=True, timeout=15)
        return True, "Nginx reloaded with HTTPS configuration."
    except subprocess.CalledProcessError as exc:
        return False, f"Nginx reload failed: {exc}"
    except Exception as exc:
        return False, f"Nginx config write failed: {exc}"