import os
from functools import wraps
from flask import (
    Blueprint, render_template, redirect, url_for,
    request, session, flash, jsonify, current_app
)
from app.forms.setup_forms import (
    BrandingForm, NetworkForm, LDAPForm, SSOForm,
    SMTPForm, AdminAccountForm, WebexTokenForm
)
from app.services import setup_service as svc
from app.services.nginx_service import write_https_nginx_config

setup_bp = Blueprint("setup", __name__, template_folder="../templates/setup")

TOTAL_STEPS = 7
STEP_TITLES = {
    1: "Branding",
    2: "Network & TLS",
    3: "LDAP Directory",
    4: "Single Sign-On",
    5: "Email (SMTP)",
    6: "Admin Account",
    7: "Webex Integration",
}


def setup_only(f):
    """Decorator: block setup routes if setup is already complete."""
    @wraps(f)
    def decorated(*args, **kwargs):
        if os.environ.get("APP_STATE") == "setup_complete":
            flash("Setup has already been completed.", "info")
            return redirect(url_for("admin.dashboard"))
        return f(*args, **kwargs)
    return decorated


def _step_context(step: int) -> dict:
    """Build shared context dict for all setup templates."""
    completed = session.get("setup_completed_steps", [])
    return {
        "current_step":   step,
        "total_steps":    TOTAL_STEPS,
        "step_titles":    STEP_TITLES,
        "completed_steps": completed,
        "progress_pct":   int((len(completed) / TOTAL_STEPS) * 100),
    }


# ── Index — redirect to current step ─────────────────────────────────────────
@setup_bp.route("/", methods=["GET"])
@setup_only
def index():
    completed = session.get("setup_completed_steps", [])
    next_step = len(completed) + 1
    if next_step > TOTAL_STEPS:
        return redirect(url_for("setup.complete"))
    return redirect(url_for(f"setup.step{next_step}"))


# ── Step 1 — Branding ─────────────────────────────────────────────────────────
@setup_bp.route("/step/1", methods=["GET", "POST"])
@setup_only
def step1():
    form = BrandingForm()
    _populate_timezone_choices(form)

    if form.validate_on_submit():
        logo_path = ""
        if form.logo.data and form.logo.data.filename:
            ok, result = svc.save_logo(form.logo.data)
            if not ok:
                flash(result, "danger")
                return render_template(
                    "step1_branding.html", form=form, **_step_context(1)
                )
            logo_path = result
            flash(f"Logo uploaded: {logo_path}", "success")

        svc.save_branding(form.data, logo_path)
        _mark_step_complete(1)
        flash("Branding settings saved.", "success")
        return redirect(url_for("setup.step2"))

    return render_template("step1_branding.html", form=form, **_step_context(1))


# ── Step 2 — Network / TLS ────────────────────────────────────────────────────
@setup_bp.route("/step/2", methods=["GET", "POST"])
@setup_only
def step2():
    form = NetworkForm()

    if form.validate_on_submit():
        cert_mode = form.cert_mode.data
        fqdn      = form.fqdn.data.strip()

        if cert_mode == "letsencrypt":
            if not form.le_email.data:
                flash("An email address is required for Let's Encrypt.", "danger")
                return render_template("step2_network.html", form=form, **_step_context(2))
            if not form.le_agree_tos.data:
                flash("You must agree to the Let's Encrypt Terms of Service.", "danger")
                return render_template("step2_network.html", form=form, **_step_context(2))

            flash("Requesting Let's Encrypt certificate... this may take up to 60 seconds.", "info")
            ok, msg = svc.request_letsencrypt(fqdn, form.le_email.data)
            if not ok:
                flash(msg, "danger")
                return render_template("step2_network.html", form=form, **_step_context(2))
            flash(msg, "success")

        elif cert_mode == "custom_ca":
            if not (form.ca_cert_file.data and form.server_cert_file.data and form.server_key_file.data):
                flash("All three certificate files (CA cert, server cert, private key) are required.", "danger")
                return render_template("step2_network.html", form=form, **_step_context(2))

            ok, msg = svc.save_custom_cert(
                form.ca_cert_file.data,
                form.server_cert_file.data,
                form.server_key_file.data,
            )
            if not ok:
                flash(msg, "danger")
                return render_template("step2_network.html", form=form, **_step_context(2))
            flash(msg, "success")

        else:  # selfsigned — already generated by installer
            flash("Using self-signed certificate generated during installation.", "info")

        svc.save_network(fqdn, cert_mode)
        _mark_step_complete(2)
        flash("Network settings saved.", "success")
        return redirect(url_for("setup.step3"))

    return render_template("step2_network.html", form=form, **_step_context(2))


# ── Step 3 — LDAP ────────────────────────────────────────────────────────────
@setup_bp.route("/step/3", methods=["GET", "POST"])
@setup_only
def step3():
    form = LDAPForm()

    if form.validate_on_submit():
        if form.ldap_enabled.data:
            # Test connection before saving
            ok, msg = svc.test_ldap_connection(
                host=form.ldap_host.data,
                port=form.ldap_port.data or 389,
                use_ssl=form.ldap_use_ssl.data,
                use_starttls=form.ldap_use_starttls.data,
                bind_dn=form.ldap_bind_dn.data,
                bind_password=form.ldap_bind_password.data,
            )
            if not ok:
                flash(f"LDAP connection failed: {msg}", "danger")
                return render_template("step3_ldap.html", form=form, **_step_context(3))
            flash(msg, "success")

        svc.save_ldap(form.data)
        _mark_step_complete(3)
        flash("LDAP settings saved.", "success")
        return redirect(url_for("setup.step4"))

    return render_template("step3_ldap.html", form=form, **_step_context(3))


# ── AJAX: Test LDAP (called from the "Test Connection" button) ────────────────
@setup_bp.route("/api/test-ldap", methods=["POST"])
@setup_only
def test_ldap_ajax():
    data = request.get_json(force=True)
    ok, msg = svc.test_ldap_connection(
        host=data.get("host", ""),
        port=int(data.get("port", 389)),
        use_ssl=data.get("use_ssl", False),
        use_starttls=data.get("use_starttls", False),
        bind_dn=data.get("bind_dn", ""),
        bind_password=data.get("bind_password", ""),
    )
    return jsonify({"success": ok, "message": msg})


# ── Step 4 — SSO ──────────────────────────────────────────────────────────────
@setup_bp.route("/step/4", methods=["GET", "POST"])
@setup_only
def step4():
    form = SSOForm()

    if form.validate_on_submit():
        # Handle SAML metadata XML upload
        if form.sso_enabled.data and form.saml_metadata_file.data:
            _parse_saml_metadata(form)

        svc.save_sso(form.data)
        _mark_step_complete(4)
        flash("SSO settings saved.", "success")
        return redirect(url_for("setup.step5"))

    return render_template("step4_sso.html", form=form, **_step_context(4))


# ── Step 5 — SMTP ─────────────────────────────────────────────────────────────
@setup_bp.route("/step/5", methods=["GET", "POST"])
@setup_only
def step5():
    form = SMTPForm()

    if form.validate_on_submit():
        svc.save_smtp(form.data)

        # Optional test email
        if form.smtp_test_recipient.data:
            ok, msg = svc.test_smtp(
                host=form.smtp_host.data,
                port=form.smtp_port.data,
                use_tls=form.smtp_use_tls.data,
                use_ssl=form.smtp_use_ssl.data,
                username=form.smtp_username.data,
                password=form.smtp_password.data,
                from_addr=form.smtp_from_address.data,
                to_addr=form.smtp_test_recipient.data,
            )
            flash(msg, "success" if ok else "warning")

        _mark_step_complete(5)
        flash("SMTP settings saved.", "success")
        return redirect(url_for("setup.step6"))

    return render_template("step5_smtp.html", form=form, **_step_context(5))


# ── AJAX: Test SMTP ───────────────────────────────────────────────────────────
@setup_bp.route("/api/test-smtp", methods=["POST"])
@setup_only
def test_smtp_ajax():
    data = request.get_json(force=True)
    ok, msg = svc.test_smtp(
        host=data.get("host", ""),
        port=int(data.get("port", 587)),
        use_tls=data.get("use_tls", True),
        use_ssl=data.get("use_ssl", False),
        username=data.get("username", ""),
        password=data.get("password", ""),
        from_addr=data.get("from_addr", ""),
        to_addr=data.get("to_addr", ""),
    )
    return jsonify({"success": ok, "message": msg})


# ── Step 6 — Admin Account ────────────────────────────────────────────────────
@setup_bp.route("/step/6", methods=["GET", "POST"])
@setup_only
def step6():
    form = AdminAccountForm()

    if form.validate_on_submit():
        ok, msg = svc.create_platform_admin(form.data)
        if not ok:
            flash(msg, "danger")
            return render_template("step6_admin.html", form=form, **_step_context(6))

        _mark_step_complete(6)
        flash(msg, "success")
        return redirect(url_for("setup.step7"))

    return render_template("step6_admin.html", form=form, **_step_context(6))


# ── Step 7 — Webex Token ──────────────────────────────────────────────────────
@setup_bp.route("/step/7", methods=["GET", "POST"])
@setup_only
def step7():
    form = WebexTokenForm()
    webex_info = session.get("webex_info", {})

    if form.validate_on_submit():
        ok, msg, info = svc.test_webex_token(form.webex_access_token.data)
        if not ok:
            flash(msg, "danger")
            return render_template("step7_webex.html", form=form,
                                   webex_info={}, **_step_context(7))

        session["webex_info"] = info
        org_id = form.webex_org_id.data or info.get("org_id", "")
        svc.save_webex(form.webex_access_token.data, org_id)

        _mark_step_complete(7)
        flash(f"Webex token validated. Connected to org: {info.get('org_name')}", "success")
        return redirect(url_for("setup.finalize"))

    return render_template("step7_webex.html", form=form,
                           webex_info=webex_info, **_step_context(7))


# ── AJAX: Validate Webex token live ──────────────────────────────────────────
@setup_bp.route("/api/test-webex", methods=["POST"])
@setup_only
def test_webex_ajax():
    data  = request.get_json(force=True)
    token = data.get("token", "")
    ok, msg, info = svc.test_webex_token(token)
    return jsonify({"success": ok, "message": msg, "info": info})


# ── Finalize — write HTTPS Nginx config, mark complete ────────────────────────
@setup_bp.route("/finalize", methods=["GET"])
@setup_only
def finalize():
    completed = session.get("setup_completed_steps", [])
    if len(completed) < TOTAL_STEPS:
        flash("Please complete all setup steps before finalizing.", "warning")
        return redirect(url_for("setup.index"))

    fqdn      = os.environ.get("SERVER_FQDN", "localhost")
    cert_path = os.environ.get("CERT_PATH",   "")
    key_path  = os.environ.get("KEY_PATH",    "")
    app_port  = int(os.environ.get("APP_PORT", 8080))

    ok, msg = write_https_nginx_config(fqdn, cert_path, key_path, app_port)
    if ok:
        svc.mark_setup_complete()
        flash("🎉 Setup complete! Orbit is now running over HTTPS.", "success")
    else:
        flash(f"Setup saved but Nginx HTTPS switch failed: {msg} — "
              "You may need to configure HTTPS manually.", "warning")

    session.pop("setup_completed_steps", None)
    session.pop("webex_info", None)
    return redirect(url_for("setup.complete"))


@setup_bp.route("/complete")
def complete():
    fqdn = os.environ.get("SERVER_FQDN", request.host)
    return render_template("complete.html", fqdn=fqdn)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _mark_step_complete(step: int) -> None:
    completed = session.get("setup_completed_steps", [])
    if step not in completed:
        completed.append(step)
    session["setup_completed_steps"] = completed
    session.modified = True


def _populate_timezone_choices(form) -> None:
    import pytz
    zones = [(tz, tz) for tz in pytz.common_timezones]
    form.timezone.choices = zones


def _parse_saml_metadata(form) -> None:
    """Parse uploaded SAML metadata XML and auto-fill form fields."""
    try:
        import xml.etree.ElementTree as ET
        xml_data = form.saml_metadata_file.data.read()
        root = ET.fromstring(xml_data)
        ns = {"md": "urn:oasis:names:tc:SAML:2.0:metadata",
              "ds": "http://www.w3.org/2000/09/xmldsig#"}

        entity_id = root.get("entityID", "")
        sso_el = root.find(".//md:SingleSignOnService", ns)
        slo_el = root.find(".//md:SingleLogoutService", ns)
        cert_el = root.find(".//ds:X509Certificate", ns)

        if entity_id:
            form.saml_entity_id.data = entity_id
        if sso_el is not None:
            form.saml_sso_url.data = sso_el.get("Location", "")
        if slo_el is not None:
            form.saml_slo_url.data = slo_el.get("Location", "")
        if cert_el is not None:
            form.saml_certificate.data = cert_el.text.strip()
    except Exception:
        pass   # Silent — user can fill fields manually
