from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed
from wtforms import (
    StringField, PasswordField, SelectField, BooleanField,
    IntegerField, TextAreaField, HiddenField, RadioField
)
from wtforms.validators import (
    DataRequired, Optional, Email, Length,
    NumberRange, EqualTo, URL, Regexp
)


# ── Step 1 — Branding ─────────────────────────────────────────────────────────
class BrandingForm(FlaskForm):
    app_name = StringField(
        "Application Name",
        validators=[DataRequired(), Length(min=2, max=64)],
        default="Orbit",
        render_kw={"placeholder": "Orbit"}
    )
    logo = FileField(
        "Logo File",
        validators=[
            Optional(),
            FileAllowed(["png", "svg", "jpg", "jpeg"],
                        "Only PNG, SVG, JPG files are accepted.")
        ]
    )
    primary_color = StringField(
        "Primary Brand Colour (hex)",
        validators=[
            DataRequired(),
            Regexp(r'^#[0-9A-Fa-f]{6}$', message="Must be a valid hex colour e.g. #1E40AF")
        ],
        default="#1E40AF"
    )
    accent_color = StringField(
        "Accent Colour (hex)",
        validators=[
            DataRequired(),
            Regexp(r'^#[0-9A-Fa-f]{6}$', message="Must be a valid hex colour.")
        ],
        default="#3B82F6"
    )
    company_name = StringField(
        "Company / Organisation Name",
        validators=[DataRequired(), Length(min=2, max=128)],
        render_kw={"placeholder": "ACME Corporation"}
    )
    timezone = SelectField(
        "Default Timezone",
        validators=[DataRequired()],
        default="UTC"
    )
    language = SelectField(
        "Default Language",
        choices=[
            ("en", "English"),
            ("nl", "Nederlands"),
            ("fr", "Français"),
            ("de", "Deutsch"),
            ("es", "Español"),
        ],
        default="en"
    )


# ── Step 2 — Network / FQDN / TLS ────────────────────────────────────────────
class NetworkForm(FlaskForm):
    fqdn = StringField(
        "Application FQDN",
        validators=[DataRequired(), Length(min=3, max=255)],
        render_kw={"placeholder": "orbit.company.com"}
    )
    cert_mode = RadioField(
        "TLS Certificate Mode",
        choices=[
            ("letsencrypt", "Let's Encrypt (automatic, requires public DNS)"),
            ("custom_ca",   "Custom CA / Bring Your Own Certificate"),
            ("selfsigned",  "Self-Signed (already generated by installer)"),
        ],
        default="selfsigned",
        validators=[DataRequired()]
    )
    # Let's Encrypt fields
    le_email = StringField(
        "Email for Let's Encrypt Notifications",
        validators=[Optional(), Email()],
        render_kw={"placeholder": "admin@company.com"}
    )
    le_agree_tos = BooleanField(
        "I agree to the Let's Encrypt Terms of Service",
        validators=[Optional()]
    )
    # Custom CA fields
    ca_cert_file   = FileField("CA Certificate (PEM/CRT)",
                               validators=[Optional(), FileAllowed(["pem", "crt", "cer"])])
    server_cert_file = FileField("Server Certificate (PEM/CRT)",
                                 validators=[Optional(), FileAllowed(["pem", "crt", "cer"])])
    server_key_file  = FileField("Server Private Key (PEM/KEY)",
                                 validators=[Optional(), FileAllowed(["pem", "key"])])


# ── Step 3 — LDAP ─────────────────────────────────────────────────────────────
class LDAPForm(FlaskForm):
    ldap_enabled = BooleanField("Enable LDAP Authentication", default=False)

    ldap_host = StringField(
        "LDAP Server Hostname / IP",
        validators=[Optional(), Length(max=255)],
        render_kw={"placeholder": "ldap.company.com"}
    )
    ldap_port = IntegerField(
        "Port",
        validators=[Optional(), NumberRange(min=1, max=65535)],
        default=389
    )
    ldap_use_ssl = BooleanField("Use LDAPS (SSL/TLS)", default=False)
    ldap_use_starttls = BooleanField("Use STARTTLS (upgrades plain → encrypted)", default=False)

    ldap_bind_dn = StringField(
        "Bind DN (service account)",
        validators=[Optional(), Length(max=512)],
        render_kw={"placeholder": "cn=svc-orbit,ou=service,dc=company,dc=com"}
    )
    ldap_bind_password = PasswordField(
        "Bind Password",
        validators=[Optional(), Length(max=256)]
    )
    ldap_base_dn = StringField(
        "Search Base DN",
        validators=[Optional(), Length(max=512)],
        render_kw={"placeholder": "ou=users,dc=company,dc=com"}
    )
    ldap_user_filter = StringField(
        "User Search Filter",
        validators=[Optional(), Length(max=256)],
        default="(mail={username})",
        render_kw={"placeholder": "(mail={username})"}
    )
    ldap_group_base_dn = StringField(
        "Group Search Base DN",
        validators=[Optional(), Length(max=512)],
        render_kw={"placeholder": "ou=groups,dc=company,dc=com"}
    )
    ldap_admin_group_dn = StringField(
        "GUI Admin Group DN",
        validators=[Optional(), Length(max=512)],
        render_kw={"placeholder": "cn=orbit-admins,ou=groups,dc=company,dc=com"}
    )
    ldap_user_group_dn = StringField(
        "End User Group DN",
        validators=[Optional(), Length(max=512)],
        render_kw={"placeholder": "cn=orbit-users,ou=groups,dc=company,dc=com"}
    )
    ldap_attr_email       = StringField("Email Attribute",       default="mail",        validators=[Optional()])
    ldap_attr_firstname   = StringField("First Name Attribute",  default="givenName",   validators=[Optional()])
    ldap_attr_lastname    = StringField("Last Name Attribute",   default="sn",          validators=[Optional()])
    ldap_attr_username    = StringField("Username Attribute",    default="sAMAccountName", validators=[Optional()])


# ── Step 4 — SSO ──────────────────────────────────────────────────────────────
class SSOForm(FlaskForm):
    sso_enabled = BooleanField("Enable Single Sign-On (SSO)", default=False)

    sso_provider = SelectField(
        "SSO Provider",
        choices=[
            ("",          "— Select Provider —"),
            ("azure_ad",  "Microsoft Azure AD / Entra ID"),
            ("okta",      "Okta"),
            ("google",    "Google Workspace"),
            ("saml",      "Generic SAML 2.0"),
            ("oidc",      "Generic OIDC"),
        ],
        validators=[Optional()]
    )
    sso_protocol = RadioField(
        "Protocol",
        choices=[("saml", "SAML 2.0"), ("oidc", "OpenID Connect (OIDC)")],
        default="saml",
        validators=[Optional()]
    )
    # SAML fields
    saml_entity_id       = StringField("IdP Entity ID",       validators=[Optional(), Length(max=512)])
    saml_sso_url         = StringField("IdP SSO URL",         validators=[Optional(), Length(max=512)])
    saml_slo_url         = StringField("IdP SLO URL",         validators=[Optional(), Length(max=512)])
    saml_certificate     = TextAreaField("IdP X.509 Certificate (PEM)", validators=[Optional()])
    saml_metadata_file   = FileField("OR: Upload IdP Metadata XML",
                                     validators=[Optional(), FileAllowed(["xml"])])
    saml_name_id_format  = SelectField(
        "NameID Format",
        choices=[
            ("urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress", "Email Address"),
            ("urn:oasis:names:tc:SAML:2.0:nameid-format:persistent",   "Persistent"),
            ("urn:oasis:names:tc:SAML:2.0:nameid-format:transient",    "Transient"),
        ],
        default="urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress",
        validators=[Optional()]
    )
    # OIDC fields
    oidc_client_id       = StringField("Client ID",           validators=[Optional(), Length(max=512)])
    oidc_client_secret   = PasswordField("Client Secret",     validators=[Optional(), Length(max=512)])
    oidc_discovery_url   = StringField(
        "Discovery URL (/.well-known/openid-configuration)",
        validators=[Optional(), Length(max=512)],
        render_kw={"placeholder": "https://login.microsoftonline.com/{tenant}/v2.0"}
    )
    # Attribute mapping
    sso_attr_email       = StringField("Email Attribute/Claim",      default="email",      validators=[Optional()])
    sso_attr_firstname   = StringField("First Name Attribute/Claim", default="given_name", validators=[Optional()])
    sso_attr_lastname    = StringField("Last Name Attribute/Claim",  default="family_name",validators=[Optional()])
    sso_admin_group      = StringField(
        "Admin Group Name/Claim Value",
        validators=[Optional()],
        render_kw={"placeholder": "orbit-admins"}
    )


# ── Step 5 — SMTP ─────────────────────────────────────────────────────────────
class SMTPForm(FlaskForm):
    smtp_host = StringField(
        "SMTP Server",
        validators=[DataRequired(), Length(max=255)],
        render_kw={"placeholder": "smtp.company.com"}
    )
    smtp_port = IntegerField(
        "Port",
        validators=[DataRequired(), NumberRange(min=1, max=65535)],
        default=587
    )
    smtp_use_tls = BooleanField("Use TLS (STARTTLS)", default=True)
    smtp_use_ssl = BooleanField("Use SSL (port 465)", default=False)
    smtp_username = StringField(
        "SMTP Username",
        validators=[Optional(), Length(max=255)],
        render_kw={"placeholder": "orbit@company.com"}
    )
    smtp_password = PasswordField(
        "SMTP Password",
        validators=[Optional(), Length(max=256)]
    )
    smtp_from_name    = StringField("From Display Name", default="Orbit Platform",
                                    validators=[DataRequired(), Length(max=128)])
    smtp_from_address = StringField("From Email Address",
                                    validators=[DataRequired(), Email(), Length(max=255)],
                                    render_kw={"placeholder": "noreply@company.com"})
    smtp_test_recipient = StringField(
        "Send Test Email To (optional)",
        validators=[Optional(), Email()],
        render_kw={"placeholder": "admin@company.com"}
    )


# ── Step 6 — Application Admin Account ────────────────────────────────────────
class AdminAccountForm(FlaskForm):
    admin_username = StringField(
        "Admin Username",
        validators=[
            DataRequired(),
            Length(min=3, max=64),
            Regexp(r'^[a-zA-Z0-9_.-]+$',
                   message="Only letters, numbers, dots, hyphens and underscores.")
        ],
        render_kw={"placeholder": "orbitadmin"}
    )
    admin_email = StringField(
        "Admin Email Address",
        validators=[DataRequired(), Email(), Length(max=255)],
        render_kw={"placeholder": "admin@company.com"}
    )
    admin_first_name = StringField("First Name", validators=[DataRequired(), Length(max=64)])
    admin_last_name  = StringField("Last Name",  validators=[DataRequired(), Length(max=64)])
    admin_password = PasswordField(
        "Password",
        validators=[
            DataRequired(),
            Length(min=12, max=128,
                   message="Minimum 12 characters."),
            Regexp(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[@$!%*#?&^_\-])',
                   message="Must contain uppercase, lowercase, digit and special character.")
        ]
    )
    admin_password_confirm = PasswordField(
        "Confirm Password",
        validators=[
            DataRequired(),
            EqualTo("admin_password", message="Passwords must match.")
        ]
    )


# ── Step 7 — Webex API Token ──────────────────────────────────────────────────
class WebexTokenForm(FlaskForm):
    webex_access_token = PasswordField(
        "Webex Access Token",
        validators=[DataRequired(), Length(min=50, max=2048)],
        render_kw={"placeholder": "Paste your Webex Org-level access token here"}
    )
    webex_org_id = StringField(
        "Webex Organisation ID (optional — auto-detected if left blank)",
        validators=[Optional(), Length(max=512)],
        render_kw={"placeholder": "Y2lzY29zcGFyazovL..."}
    )
