"""initial

Revision ID: 5815db5cab68
Revises: 
Create Date: 2026-03-27 22:00:06.647292
"""
from alembic import op
import sqlalchemy as sa


revision = '5815db5cab68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('encrypted', sa.Boolean(), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('updated_by', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_config_key'), 'app_config', ['key'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=True),
    sa.Column('resource', sa.String(length=200), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=300), nullable=True),
    sa.Column('http_method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=200), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('row_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_category'), 'audit_logs', ['category'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_table('calling_search_spaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cucm_uuid', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('partitions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cucm_uuid')
    )
    op.create_index(op.f('ix_calling_search_spaces_name'), 'calling_search_spaces', ['name'], unique=True)
    op.create_table('device_pools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cucm_uuid', sa.String(length=40), nullable=True),
    sa.Column('date_time_group', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('srst_reference', sa.String(length=128), nullable=True),
    sa.Column('calling_search_space', sa.String(length=128), nullable=True),
    sa.Column('media_resource_group_list', sa.String(length=128), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cucm_uuid')
    )
    op.create_index(op.f('ix_device_pools_name'), 'device_pools', ['name'], unique=True)
    op.create_table('expressways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('host', sa.String(length=200), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('serial_number', sa.String(length=60), nullable=True),
    sa.Column('software_version', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('uptime', sa.String(length=60), nullable=True),
    sa.Column('system_name', sa.String(length=128), nullable=True),
    sa.Column('hardware_version', sa.String(length=60), nullable=True),
    sa.Column('active_calls', sa.Integer(), nullable=True),
    sa.Column('max_calls', sa.Integer(), nullable=True),
    sa.Column('active_registrations', sa.Integer(), nullable=True),
    sa.Column('max_registrations', sa.Integer(), nullable=True),
    sa.Column('mra_enabled', sa.Boolean(), nullable=True),
    sa.Column('b2b_enabled', sa.Boolean(), nullable=True),
    sa.Column('cluster_name', sa.String(length=128), nullable=True),
    sa.Column('last_polled', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expressways_name'), 'expressways', ['name'], unique=True)
    op.create_table('gateways',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cucm_uuid', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('gateway_type', sa.String(length=60), nullable=True),
    sa.Column('protocol', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('vendor', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('port_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cucm_uuid')
    )
    op.create_index(op.f('ix_gateways_name'), 'gateways', ['name'], unique=True)
    op.create_table('imp_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('jabber_id', sa.String(length=254), nullable=True),
    sa.Column('im_enabled', sa.Boolean(), nullable=True),
    sa.Column('presence_status', sa.String(length=40), nullable=True),
    sa.Column('status_message', sa.String(length=300), nullable=True),
    sa.Column('home_cluster', sa.String(length=128), nullable=True),
    sa.Column('device_name', sa.String(length=128), nullable=True),
    sa.Column('directory_uri', sa.String(length=254), nullable=True),
    sa.Column('is_ucm_synced', sa.Boolean(), nullable=True),
    sa.Column('federation_enabled', sa.Boolean(), nullable=True),
    sa.Column('compliance_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_imp_users_user_id'), 'imp_users', ['user_id'], unique=True)
    op.create_table('partitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cucm_uuid', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('time_schedule', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cucm_uuid')
    )
    op.create_index(op.f('ix_partitions_name'), 'partitions', ['name'], unique=True)
    op.create_table('phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('mac_address', sa.String(length=17), nullable=True),
    sa.Column('firmware', sa.String(length=80), nullable=True),
    sa.Column('directory_number', sa.String(length=30), nullable=True),
    sa.Column('device_pool', sa.String(length=128), nullable=True),
    sa.Column('calling_search_space', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('owner_user_id', sa.String(length=128), nullable=True),
    sa.Column('cucm_uuid', sa.String(length=40), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cluster_node', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cucm_uuid')
    )
    op.create_index(op.f('ix_phones_name'), 'phones', ['name'], unique=True)
    op.create_table('route_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=128), nullable=False),
    sa.Column('cucm_uuid', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('partition', sa.String(length=128), nullable=True),
    sa.Column('gateway', sa.String(length=128), nullable=True),
    sa.Column('route_list', sa.String(length=128), nullable=True),
    sa.Column('block_enabled', sa.Boolean(), nullable=True),
    sa.Column('urgent_priority', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cucm_uuid')
    )
    op.create_index(op.f('ix_route_patterns_pattern'), 'route_patterns', ['pattern'], unique=False)
    op.create_table('translation_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pattern', sa.String(length=128), nullable=False),
    sa.Column('cucm_uuid', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('partition', sa.String(length=128), nullable=True),
    sa.Column('calling_search_space', sa.String(length=128), nullable=True),
    sa.Column('called_party_transform', sa.String(length=128), nullable=True),
    sa.Column('calling_party_transform', sa.String(length=128), nullable=True),
    sa.Column('prefix_digits', sa.String(length=30), nullable=True),
    sa.Column('discard_digits', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cucm_uuid')
    )
    op.create_index(op.f('ix_translation_patterns_pattern'), 'translation_patterns', ['pattern'], unique=False)
    op.create_table('trunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('cucm_uuid', sa.String(length=40), nullable=True),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.Column('trunk_type', sa.String(length=40), nullable=True),
    sa.Column('device_pool', sa.String(length=128), nullable=True),
    sa.Column('calling_search_space', sa.String(length=128), nullable=True),
    sa.Column('destination_address', sa.String(length=200), nullable=True),
    sa.Column('destination_port', sa.Integer(), nullable=True),
    sa.Column('sip_profile', sa.String(length=128), nullable=True),
    sa.Column('security_profile', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cucm_uuid')
    )
    op.create_index(op.f('ix_trunks_name'), 'trunks', ['name'], unique=True)
    op.create_table('unity_mailboxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('extension', sa.String(length=30), nullable=True),
    sa.Column('dtmf_access_id', sa.String(length=30), nullable=True),
    sa.Column('mailbox_type', sa.String(length=40), nullable=True),
    sa.Column('is_vm_enabled', sa.Boolean(), nullable=True),
    sa.Column('greeting_type', sa.String(length=40), nullable=True),
    sa.Column('max_msg_length', sa.Integer(), nullable=True),
    sa.Column('cos_name', sa.String(length=128), nullable=True),
    sa.Column('partition_name', sa.String(length=128), nullable=True),
    sa.Column('unity_object_id', sa.String(length=40), nullable=True),
    sa.Column('smtp_address', sa.String(length=254), nullable=True),
    sa.Column('is_mwi_enabled', sa.Boolean(), nullable=True),
    sa.Column('send_message_on_login', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unity_object_id')
    )
    op.create_index(op.f('ix_unity_mailboxes_alias'), 'unity_mailboxes', ['alias'], unique=True)
    op.create_table('unity_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('extension', sa.String(length=30), nullable=True),
    sa.Column('smtp_address', sa.String(length=254), nullable=True),
    sa.Column('is_vm_enrolled', sa.Boolean(), nullable=True),
    sa.Column('cos_name', sa.String(length=128), nullable=True),
    sa.Column('unity_object_id', sa.String(length=40), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('ldap_type', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('unity_object_id')
    )
    op.create_index(op.f('ix_unity_users_alias'), 'unity_users', ['alias'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('first_name', sa.String(length=80), nullable=True),
    sa.Column('last_name', sa.String(length=80), nullable=True),
    sa.Column('role', sa.Enum('PLATFORM_ADMIN', 'GUI_ADMIN', 'END_USER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('auth_method', sa.String(length=20), nullable=True),
    sa.Column('sso_subject', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('zone_type', sa.String(length=60), nullable=True),
    sa.Column('peer_address', sa.String(length=200), nullable=True),
    sa.Column('peer_port', sa.Integer(), nullable=True),
    sa.Column('transport', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('direction', sa.String(length=20), nullable=True),
    sa.Column('sip_mode', sa.String(length=20), nullable=True),
    sa.Column('h323_mode', sa.String(length=20), nullable=True),
    sa.Column('search_rules', sa.Text(), nullable=True),
    sa.Column('expressway_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['expressway_id'], ['expressways.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zones_name'), 'zones', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zones_name'), table_name='zones')
    op.drop_table('zones')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_unity_users_alias'), table_name='unity_users')
    op.drop_table('unity_users')
    op.drop_index(op.f('ix_unity_mailboxes_alias'), table_name='unity_mailboxes')
    op.drop_table('unity_mailboxes')
    op.drop_index(op.f('ix_trunks_name'), table_name='trunks')
    op.drop_table('trunks')
    op.drop_index(op.f('ix_translation_patterns_pattern'), table_name='translation_patterns')
    op.drop_table('translation_patterns')
    op.drop_index(op.f('ix_route_patterns_pattern'), table_name='route_patterns')
    op.drop_table('route_patterns')
    op.drop_index(op.f('ix_phones_name'), table_name='phones')
    op.drop_table('phones')
    op.drop_index(op.f('ix_partitions_name'), table_name='partitions')
    op.drop_table('partitions')
    op.drop_index(op.f('ix_imp_users_user_id'), table_name='imp_users')
    op.drop_table('imp_users')
    op.drop_index(op.f('ix_gateways_name'), table_name='gateways')
    op.drop_table('gateways')
    op.drop_index(op.f('ix_expressways_name'), table_name='expressways')
    op.drop_table('expressways')
    op.drop_index(op.f('ix_device_pools_name'), table_name='device_pools')
    op.drop_table('device_pools')
    op.drop_index(op.f('ix_calling_search_spaces_name'), table_name='calling_search_spaces')
    op.drop_table('calling_search_spaces')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_category'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_app_config_key'), table_name='app_config')
    op.drop_table('app_config')
    # ### end Alembic commands ###
